/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    DocumentCard: typeof import('./src/components/DocumentCard/index.vue')['default']
    DocumentTree: typeof import('./src/components/DocumentTree/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMention: typeof import('element-plus/es')['ElMention']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileList: typeof import('./src/components/FileList/index.vue')['default']
    FixMenu: typeof import('./src/components/Tiptap/FixMenu/index.vue')['default']
    Form: typeof import('./src/components/Form/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    HistoryItem: typeof import('./src/components/HistoryList/HistoryItem/index.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList/index.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard/index.vue')['default']
    LibraryForm: typeof import('./src/components/LibraryForm/index.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextFooter: typeof import('./src/components/TextFooter/index.vue')['default']
    TextTable: typeof import('./src/components/TextTable/index.vue')['default']
    TextTitle: typeof import('./src/components/TextTitle/index.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap/index.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
  }
}
